spring.application.name=day17-springboot-caching

spring.datasource.url=jdbc:mysql://localhost:3306/day17_caching
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

