spring.application.name=day16-scheduler-demo


spring.datasource.url=jdbc:mysql://localhost:3306/day16db
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Enable scheduling globally
spring.task.scheduling.pool.size=5

